name: OSX Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: tag version date
      run: /bin/sh ./tag.sh
    - name: Install packages
      run: brew install gcc autoconf automake libtool binutils ;
    - name: change Makefile for OSX
      run : rm louvain-generic/Makefile ; cp louvain-generic/Makefile.osx louvain-generic/Makefile
    - name: build
      run: export AR='gcc-ar-10'; export NM='gcc-nm-10'; export RANLIB='gcc-ranlib-10'; export CXX='g++-10'; export CC='gcc-10' ;  ./build_louvain.sh
    - name: rename
      run: mv website/louvain_linux.tar.gz website/louvain_osx.tar.gz
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
          branch: osx  # The branch the action should deploy to.
          folder: website/  # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true 
